# Generated by Django 4.1.7 on 2023-03-29 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_apartment_num', models.CharField(max_length=255, null=True)),
                ('company_street', models.CharField(max_length=255, null=True)),
                ('company_city', models.CharField(max_length=255, null=True)),
                ('company_state', models.CharField(max_length=255, null=True)),
                ('company_country', models.CharField(max_length=255, null=True)),
                ('company_contact_number', models.BigIntegerField()),
                ('company_email_address', models.EmailField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('role_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('emp_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empRole', to='adminDashboardApp.role')),
                ('emp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='male', max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('contact_number', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('department_name', models.CharField(choices=[('hr', 'Hr'), ('backoffice', 'Backoffice'), ('developer', 'Developer'), ('designer', 'Designer'), ('business_development', 'Business_Development'), ('admin', 'Admin')], default='hr', max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='adminDashboardApp.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeAttendance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminUserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('roles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
